Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -48,7 +48,7 @@ jobs:
             docker cp "$f" $CONTAINER_NAME:"$STAGING_DIR/$f"
           done
         
-      - name: Run CD steps inside n8n container
+      - name: Retrieve secrets from vault and apply credentials
         run: |
           docker exec \
             -e ACTIONS_ID_TOKEN_REQUEST_TOKEN="$ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
@@ -107,22 +107,55 @@ jobs:
                   envsubst < "$f" > "$f.tmp" && mv "$f.tmp" "$f"
                 done
               fi
-
-              echo "[*] Running deploy script"
-              sh "$STAGING_DIR/deploy.sh"
+          '
+      - name: Deploy to staging
+        id: deploy_step
+        run: |
+          docker exec -u root \
+            -e N8N_STAGING_API_KEY="$N8N_STAGING_API_KEY" \
+            -e BASE_URL="$BASE_URL" \
+            -e HEALTH_URL="$env.HEALTH_URL" \
+            $CONTAINER_NAME \
+            sh -lc '
+              set -euo pipefail
               
-              echo "[*] Installing dependencies"
-
+              echo "[*] Installing tester dependencies"
               cd "$STAGING_DIR/n8n-workflow-tester"
               npm install
-              
+
+              echo "[*] Installing root dependencies"
               cd "$STAGING_DIR"
               npm install
 
               echo "[*] Run Prisma migrations"
               npx prisma migrate deploy
               npx prisma generate
-              
-              echo "[*} Running tests"
-              npm test
-          '
+
+              echo "[*] Running deploy script"
+              sh "$STAGING_DIR/deploy.sh"
+            '
+
+      - name: Run post-deploy tests
+        id: test_step
+        run: |
+          docker exec -u root -e ENV="$ENV" $CONTAINER_NAME sh -lc 'cd $STAGING_DIR && npm test'
+
+      - name: Run rollback if deploy OR tests failed
+        if: steps.deploy_step.outcome == 'failure' || steps.test_step.outcome == 'failure'
+        run: |
+          if [ "${{ steps.deploy_step.outcome }}" = "failure" ]; then
+            echo "Deployment failed — rolling back"
+          elif [ "${{ steps.test_step.outcome }}" = "failure" ]; then
+            echo "Post-deployment tests failed — rolling back"
+          fi
+      
+          docker exec -u root \
+            -e N8N_STAGING_API_KEY="$N8N_STAGING_API_KEY" \
+            -e BASE_URL="$BASE_URL" \
+            -e HEALTH_URL="$HEALTH_URL" \
+            $CONTAINER_NAME \
+            sh -lc 'sh $STAGING_DIR/rollback.sh && exit 1"
+      
+          - name: Show n8n logs
+            if: failure()
+            run: docker logs n8n
